# Generated by Django 3.2.6 on 2021-09-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=20)),
                ('contact_no', models.IntegerField()),
                ('addmission_date', models.DateField()),
                ('ward_no', models.IntegerField()),
                ('Amount', models.IntegerField()),
            ],
        ),
    ]
