# Generated by Django 3.2.6 on 2021-09-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='add_detail',
            old_name='Amount',
            new_name='amount',
        ),
    ]
