# Generated by Django 3.2.6 on 2021-09-16 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20210915_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=30)),
                ('contact_no', models.IntegerField()),
                ('appointment_date', models.DateField()),
                ('disease', models.CharField(max_length=40)),
            ],
        ),
    ]
